---
development:
  dialect: mysql
  database: sales
  user: laboremus
  password: laboremus
  host: 127.0.0.1
  pool: 10

test:
  url:
    {
      {
        envOr "TEST_DATABASE_URL" "postgres://laboremus:laboremus@127.0.0.1:5432/api_test?sslmode=disable",
      },
    }

production:
  url:
    {
      {
        envOr "DATABASE_URL" "mysql://laboremus:laboremus@127.0.0.1:5432/sales?sslmode=disable",
      },
    }
